### ISSUE TITLE
Display different error message if failing in NODE_ENV = test

### ISSUE THREAD

**Issue by RhysSullivan** [t3-oss/t3-env#104]
Lots of testing frameworks (Vitest, Cypress) require a prefix when running tests for env vars. When the validation fails in a test env, the error message should be different suggesting that the user should look into if their testing framework requires a prefix for env vars to be loaded

**Comment by juliusmarminge** [comment]
Unfortunately, I don't think there is any framework agnostic way to do this, since accessing `process.env.NODE_ENV` isn't compatible with some setups.

We've previously had to revert the default `skipValidation: !!process.env.SKIP_ENV_VALIDATION` for this reason, and just now I declined #103 for the same reason.

Maybe this can be added as a callout in the docs or something?
