### ISSUE TITLE
Inline server variables are not populating correctly?

### ISSUE THREAD

**Issue by baptisteArno** [t3-oss/t3-env#106]
1. Go to `examples/nextjs`
2. Mark both `NEXT_PUBLIC_GREETING` and `SECRET` as optional
  ```mjs
  export const env = createEnv({
    client: {
      NEXT_PUBLIC_GREETING: z.string().optional(),
    },
    server: {
      SECRET: z.string().optional(),
    },
    shared: {
      NODE_ENV: z.enum(["development", "production"]),
    },
    experimental__runtimeEnv: {
      NODE_ENV: process.env.NODE_ENV,
      NEXT_PUBLIC_GREETING: process.env.NEXT_PUBLIC_GREETING,
    },
  });
  ```
3. Run `pnpm run build`
4. Run `NEXT_PUBLIC_GREETING="yo" SECRET="haha" pnpm start`
5. Navigate to `localhost:3000`
6. The inlined vars are not displayed.

Am I missing something?

**Comment by juliusmarminge** [comment]
hmm what platform? unix?

**Comment by juliusmarminge** [comment]
No: 
<img width="909" alt="CleanShot 2023-08-16 at 18 09 00@2x" src="https://github.com/t3-oss/t3-env/assets/51714798/d4658794-dea5-411b-a154-61fc2407331d">

**Comment by chungweileong94** [comment]
This is actually an expected result, as the page is a static page, which mean the env needs to be presented during build time. Since you didn't specify the env in `pnpm build` command, NextJS will build the static page with empty env.

So the proper steps will be:
1. `NEXT_PUBLIC_GREETING="yo" SECRET="haha" pnpm build`
2. `NEXT_PUBLIC_GREETING="yo" SECRET="haha" pnpm start`

**Comment by baptisteArno** [comment]
Ok, got it, that make sense I guess :)
