### ISSUE TITLE
'skipValidation' doesn't set defaults and / or makes type coercion

### ISSUE THREAD

**Issue by drinchev** [t3-oss/t3-env#155]
Using : 

```js
export const env = createEnv({
  server: {
    MY_FLAG: z
      .string()
      .default("true")
      .transform((s) => s !== "false" && s !== "0"),
  },
  client: {},
  runtimeEnv: {
    MY_FLAG: process.env.MY_FLAG,
  },
  skipValidation: !!process.env.SKIP_ENV_VALIDATION,
  emptyStringAsUndefined: true,
});

console.log(env);
```

and running : 

```shell
$ node ./src/env.js
{ MY_FLAG: true }
$ MY_FLAG=0 node ./src/env.js
{ MY_FLAG: false }
$ SKIP_ENV_VALIDATION=1 node ./src/env.js
{ MY_FLAG: undefined }
$ SKIP_ENV_VALIDATION=1 MY_FLAG=0 node ./src/env.js
{ MY_FLAG: '0' }
```

I would expect the defaults to be set, as well as the type coercion to pass.

**Comment by chungweileong94** [comment]
I see what you mean, this is a hard one.

So the validation is basically doing Zod safe parse under the hood, if you skip it, you will get the original env values without parsing.

The thing is we can get the transform value without parsing it, not that I know of. But I agree with you, it isn't that nice.

**Comment by juliusmarminge** [comment]
I don't think this is possible, if the parser doesn't run you wont get your default values, and I don't think we can like, partially, run them?

**Comment by jh0ker** [comment]
In case anyone else finds this, this is my jank solution:

```ts
  // Before:
  // skipValidation: !!process.env.SKIP_ENV_VALIDATION,
  
  // Now:
  // @ts-expect-error - We actually want to continue with invalid env vars if SKIP_ENV_VALIDATION is set
  onValidationError: !!process.env.SKIP_ENV_VALIDATION
    ? (error) => console.warn(error.toString())
    : (error) => {
        console.error(
          "❌ Invalid environment variables:",
          error.flatten().fieldErrors,
        );
        throw new Error("Invalid environment variables");
      },
```

**Comment by jh0ker** [comment]
I encountered this issue earlier and thought I would be able to circumvent this by registering a custom `onValidationError`, but that didn't actually work. I managed to get a satisfactory result but I had to resort to to `patch-package`.

The idea for the fix is actually simple. 

> I don't think we can like, partially, run them?

As it turns out, [zod does indeed have a `.partial()` method](https://github.com/colinhacks/zod?tab=readme-ov-file#partial), so I basically just applied that [around here](https://github.com/t3-oss/t3-env/blob/a1b43717a5166475290614ae7b638a549a03bf1f/packages/core/src/index.ts#L233-L234) for both objects, if `opts.skipValidation` is set. I also removed the early `return` related to this. 

In effect this means that even with an empty environment, you still get all the default values, and those you do have get parsed & validated correctly. So this isn't exactly the same as "skipping the validation", however it seems much more useful to me. Perhaps there are also unintended side-effects of this that I am not seeing.

Is this something you'd consider adding to the library @juliusmarminge? I'd be happy to contribute as well.
