### ISSUE TITLE
Tests should probably use `.toEqual()` instead of `.toMatchObject()`

### ISSUE THREAD

**Issue by b0o** [t3-oss/t3-env#156]
For example, in this test:

https://github.com/t3-oss/t3-env/blob/63a7fed1cb85e05d59c1c3c87e5b434cc8a353cc/packages/core/test/smoke.test.ts#L371-L382

It seems the intent of this test is to ensure that server-only vars aren't available in the `env` object on the client, but Vitest's [`toMatchObject`](https://vitest.dev/api/expect.html#tomatchobject) checks if the expected object is a *subset* of the actual object. If we change this to `toEqual`, we see that the server-only environment variable is present:

```
 FAIL  test/smoke.test.ts > shared can be accessed on both server and client > client
AssertionError: expected { BAR: 'bar', …(2) } to deeply equal { NODE_ENV: 'development', …(1) }
 ❯ test/smoke.test.ts:376:17
    374|     globalThis.window = {} as any;
    375|
    376|     expect(env).toEqual({
       |                 ^
    377|       NODE_ENV: "development",
    378|       FOO_BAR: "foo",

  - Expected  - 1
  + Received  + 0

    {
  +   BAR: 'bar',
      FOO_BAR: 'foo',
      NODE_ENV: 'development',
    }
```

**Comment by chungweileong94** [comment]
Oh I didn't know about that, nice catch!

However, in this particular test case `shared can be accessed on both server and client`, the `globalThis.window = {} as any` doesn't really work, plus the `createEnv` is being called in "server-side". We should do `global.window = {} as any` to simulate client, before calling `createEnv`.

Will apply the fix when I have time, but feel free to submit a PR.

**Comment by chungweileong94** [comment]
Interesting, I actually didn't know that🤔 But I don't think we have to change `toEqual` to `toMatchObject` for every test cases, except for this particular test case `shared can be accessed on both server and client > client`.

The reason why when you change the `toMatchObject` to `toEqual` will fail this test case is that, we actually called `createEnv` before `globalThis.window = {} as any`, which mean the `env` was created in server mode and the  `globalThis.window = {} as any` is pretty much doing nothing here.

**Comment by b0o** [comment]
> But I don't think we have to change toEqual to toMatchObject for every test cases

Even in the other test cases, is there a reason it's preferable to only check for a subset versus full equality? I feel like this could lead to other edge cases slipping through.

**Comment by chungweileong94** [comment]
> Edit: I actually do see one reason not to switch everything to `toEqual`: it seems Vitest tries to access a `nodeType` property on the object when using `toEqual` which triggers the Proxy to throw an error if `isServer` is `false`.

Exactly, I do agree using `toEqual` is preferable for t3-env, but because of the proxy we can't use it for `isServer: false`. However, we can workaround by expecting an error if client try to access server env prop https://github.com/t3-oss/t3-env/pull/157/files#r1432191490.

For `isServer: true`, both `toEqual` and `toMatchObject` are fine, but there are some cases where I personally think we might want to avoid using `toEqual`, as some compiler might include props like `__esModule` (https://github.com/t3-oss/t3-env/blob/63a7fed1cb85e05d59c1c3c87e5b434cc8a353cc/packages/core/index.ts#L237C11-L237C11) as part of the `env` object, but so far I didn't notice such thing happen in Vitest🤷
